#!/usr/bin/env python3
"""
Converts a PEM private key + certificate, plus secrets from .env, into
include/device_creds.h so they're all embedded in the firmware at compile
time and never hardcoded in main.cpp.

Usage: python3 make_header.py device.key device.crt include/device_creds.h
"""
import sys
from pathlib import Path


def load_env(path: Path) -> dict:
    env = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def require(env: dict, key: str) -> str:
    value = env.get(key)
    if not value:
        print(f"Missing {key} in .env -- copy .env.example to .env and fill it in.")
        sys.exit(1)
    return value


def c_string(value: str) -> str:
    # Values go through plain double-quoted C strings (not raw strings),
    # so escape anything that would break that.
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <key.pem> <cert.pem> <out_header.h>")
        sys.exit(1)

    key_path, cert_path, out_path = (Path(p) for p in sys.argv[1:4])
    project_root = Path(__file__).resolve().parent.parent
    env = load_env(project_root / ".env")

    wifi_ssid = require(env, "WIFI_SSID")
    wifi_password = require(env, "WIFI_PASSWORD")
    auth_token = require(env, "AUTH_TOKEN")

    key_pem = key_path.read_text()
    cert_pem = cert_path.read_text()

    header = f"""#pragma once
// AUTO-GENERATED by tools/make_header.py from .env -- do NOT commit this file.
// Contains the device's private key and network/auth secrets.

static const char DEVICE_KEY_PEM[] = R"EOF(
{key_pem.strip()}
)EOF";

static const char DEVICE_CERT_PEM[] = R"EOF(
{cert_pem.strip()}
)EOF";

static const char WIFI_SSID[]     = "{c_string(wifi_ssid)}";
static const char WIFI_PASSWORD[] = "{c_string(wifi_password)}";
static const char AUTH_TOKEN[]    = "{c_string(auth_token)}";
"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
