#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <WiFiServerSecure.h>
#include <lwip/napt.h>
#include <lwip/dns.h>
#include "device_creds.h"   // generated by tools/gen_creds.sh from .env, do NOT commit

// ---- Config -----------------------------------------------------------
const uint16_t TLS_PORT = 8443;
// WIFI_SSID, WIFI_PASSWORD, AUTH_TOKEN, SOFTAP_SSID, SOFTAP_PASSWORD all
// come from device_creds.h, generated from .env.

// NAT table size -- deliberately much smaller than the 1000-entry reference
// example, since that example runs with nothing else in memory. Each entry
// is ~24 bytes; watch the heap prints in setup() and raise this only if
// there's real headroom to spare once the TLS server is also running.
#define NAPT_MAX 64
#define NAPT_PORT_MAX 10

// ---- TLS server ---------------------------------------------------------
BearSSL::WiFiServerSecure server(TLS_PORT);
BearSSL::X509List   serverCert(DEVICE_CERT_PEM);
BearSSL::PrivateKey serverKey(DEVICE_KEY_PEM);

// On this core version, setECCert takes (chain, cert_issuer_key_type, key).
// BR_KEYTYPE_EC is correct here because the cert is self-signed by the same
// EC key -- if you ever chain to an RSA-signed intermediate CA instead,
// this middle argument would need to be BR_KEYTYPE_RSA.

void setup() {
  Serial.begin(115200);
  delay(200);
  Serial.printf("Heap at boot: %u\n", ESP.getFreeHeap());

  // AP_STA: stay connected to home WiFi as a station AND host our own
  // network at the same time -- this is what makes NAT between the two
  // possible at all.
  WiFi.mode(WIFI_AP_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(400);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("STA IP: ");
  Serial.println(WiFi.localIP());

#if LWIP_FEATURES && !LWIP_IPV6
  // AP clients get DHCP info from the ESP by default, including a DNS
  // pointer to the ESP itself -- which can't resolve anything. Point it at
  // the real upstream DNS server we got from the STA connection instead,
  // or AP clients will get IP connectivity but no working hostnames.
  WiFi.softAPDhcpServer().setDns(WiFi.dnsIP(0));

  WiFi.softAP(SOFTAP_SSID, SOFTAP_PASSWORD);
  Serial.print("AP IP: ");
  Serial.println(WiFi.softAPIP());

  Serial.printf("Heap before NAPT init: %u\n", ESP.getFreeHeap());
  err_t napt_ret = ip_napt_init(NAPT_MAX, NAPT_PORT_MAX);
  Serial.printf("ip_napt_init: ret=%d (OK=%d)\n", (int)napt_ret, (int)ERR_OK);
  if (napt_ret == ERR_OK) {
    napt_ret = ip_napt_enable_no(SOFTAP_IF, 1);
    Serial.printf("ip_napt_enable_no(SOFTAP_IF): ret=%d\n", (int)napt_ret);
    if (napt_ret == ERR_OK) {
      Serial.println("NAT bridge active: AP clients now routed through STA uplink");
    }
  }
  if (napt_ret != ERR_OK) {
    Serial.println("NAPT setup FAILED -- AP clients will have no internet route");
  }
  Serial.printf("Heap after NAPT init: %u\n", ESP.getFreeHeap());
#else
  Serial.println("NAPT not available in this lwIP build -- AP hosted but not routed");
#endif

  server.setECCert(&serverCert, BR_KEYTYPE_EC, &serverKey);
  server.begin();
  Serial.println("TLS control server listening");
  Serial.printf("Heap after full setup: %u\n", ESP.getFreeHeap());
}

void handleClient(WiFiClientSecure& client) {
  client.setTimeout(5000);

  String token = client.readStringUntil('\n');
  token.trim();
  if (token != AUTH_TOKEN) {
    client.println("AUTH_FAIL");
    client.stop();
    return;
  }
  client.println("AUTH_OK");

  while (client.connected()) {
    if (client.available()) {
      String cmd = client.readStringUntil('\n');
      cmd.trim();
      if (cmd.length() == 0) continue;

      if (cmd == "PING") {
        client.println("PONG");
      } else if (cmd == "STATUS") {
        client.print("uptime_ms=");
        client.println(millis());
      } else if (cmd == "QUIT") {
        client.println("BYE");
        client.flush();
        break;
      } else {
        // Placeholder -- this is where actual GPIO / control commands go.
        client.println("ERR unknown command");
      }
      client.flush();
    }
    delay(5);
  }
  client.stop();
}

void loop() {
  WiFiClientSecure client = server.available();
  if (client) {
    Serial.println("Client connected");
    handleClient(client);
    Serial.println("Client disconnected");
  } else {
    delay(100);  // yield to WiFi/lwIP stack + feed the watchdog when idle
  }
}

