#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <WiFiServerSecure.h>
#include "device_creds.h"   // generated by tools/gen_creds.sh from .env, do NOT commit

// ---- Config -----------------------------------------------------------
const uint16_t TLS_PORT = 8443;
// WIFI_SSID, WIFI_PASSWORD, and AUTH_TOKEN now come from device_creds.h,
// generated from .env -- nothing secret is hardcoded in this file anymore.

// ---- TLS server ---------------------------------------------------------
BearSSL::WiFiServerSecure server(TLS_PORT);
BearSSL::X509List   serverCert(DEVICE_CERT_PEM);
BearSSL::PrivateKey serverKey(DEVICE_KEY_PEM);

// On this core version, setECCert takes (chain, cert_issuer_key_type, key).
// BR_KEYTYPE_EC is correct here because the cert is self-signed by the same
// EC key -- if you ever chain to an RSA-signed intermediate CA instead,
// this middle argument would need to be BR_KEYTYPE_RSA.

void setup() {
  Serial.begin(115200);
  delay(200);

  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to WiFi");
  while (WiFi.status() != WL_CONNECTED) {
    delay(400);
    Serial.print(".");
  }
  Serial.println();
  Serial.print("IP: ");
  Serial.println(WiFi.localIP());

  server.setECCert(&serverCert, BR_KEYTYPE_EC, &serverKey);
  server.begin();
  Serial.println("TLS control server listening");
}

void handleClient(WiFiClientSecure& client) {
  client.setTimeout(5000);

  String token = client.readStringUntil('\n');
  token.trim();
  if (token != AUTH_TOKEN) {
    client.println("AUTH_FAIL");
    client.stop();
    return;
  }
  client.println("AUTH_OK");

  while (client.connected()) {
    if (client.available()) {
      String cmd = client.readStringUntil('\n');
      cmd.trim();
      if (cmd.length() == 0) continue;

      if (cmd == "PING") {
        client.println("PONG");
      } else if (cmd == "STATUS") {
        client.print("uptime_ms=");
        client.println(millis());
      } else if (cmd == "QUIT") {
        client.println("BYE");
        client.flush();
        break;
      } else {
        // Placeholder -- this is where actual GPIO / control commands go.
        client.println("ERR unknown command");
      }
      client.flush();
    }
    delay(5);
  }
  client.stop();
}

void loop() {
  WiFiClientSecure client = server.available();
  if (client) {
    Serial.println("Client connected");
    handleClient(client);
    Serial.println("Client disconnected");
  } else {
    delay(100);  // yield to WiFi/lwIP stack + feed the watchdog when idle
  }
}
